### ISSUE TITLE
Feature request: parameter to avoid 13F-HR/A fillings [Amends]

### ISSUE THREAD

**Issue by philsv** [git-shogg/finsec#7]
Hello @git-shogg,

I would love to be able to exclude any 13F-HR/A Fillings in my search, so I can always get the latest 13F-HR Filling.

For example right now with Berkshire Hathaway this code:

```python
filing = Filing("0001067983")
filing_df = filing.latest_13f_filing
print(filing_df)
```

would get me:

```
  Name of issuer Title of class      CUSIP Share or principal type  Holding value  Share or principal amount count
0  CHUBB LIMITED            COM  H1467J104                      SH     4542600000                         20100000
```

This is undesirable for my usecase. 

Would this be possible to include this into `_get_last_100_13f_filings_url(self)`?

or is there a way to aggregate all 13F-HR and 13F-HR/A Fillings for a specific Filing Date?

**Comment by git-shogg** [comment]
Hi @philsv, thanks for raising this one (sounds like a good feature request) I'll have a look into it.

**Comment by philsv** [comment]
@git-shogg If you want some help on this let me know

**Comment by git-shogg** [comment]
Hi @philsv , take a look at the [feature branch](https://github.com/git-shogg/finsec/tree/feature/address_13f_amendments) I've put together for this, is this along the lines of what you are after? My only concern is that the 13F-HR/A documents represent amendments to previous 13F filings (and this feature I've created, completely ignores the amendments). So I would prefer if there was a way to take into account these amendments in the latest overall holdings returned by `finsec` (rather than ignoring the amendment all together). In the case of Berkshire I am not sure how many shares of CHUBB they have ended up holding (original 13F filing stated 25,923,840 shares, second amendment stated 8,143,530 shares, third amendment stated 20,100,000 shares), do you happen to know which is correct? Or if it is a sum of amendment 2 and 3 to get overall holdings? I'm not 100% sure how to build for this yet because amendments seem to be applied in an inconsistent manner (for example the September 2023 filing amendment for Berkshire seems to repeat the entire holdings again for Berkshire, whereas the March 2024 filing amendment only shows a single stock "CHUBB").

**Comment by philsv** [comment]
@git-shogg there are 2 ways of 13F-HR/A filling NEW HOLDINGS or RESTATEMENT.

A restatement can be due to many reasons:
"fraud, misapplication of accounting principles, clerical mistakes, or new information" as some examples. As I understand them they are the total holdings as of the time but with necessary changes. New holdings are just the particular change in the portfolio.

For example:
Q3-2023 13F-HR/A filling
You can find the " RESTATEMENT" string in the primary doc.
https://www.sec.gov/Archives/edgar/data/1067983/000095012323011029/primary_doc.xml

Also for NEW HOLDINGS:
Q4-2023 13F-HR/A filling
https://www.sec.gov/Archives/edgar/data/1067983/000095012324005664/primary_doc.xml

13.info does a pretty good job at this, you can compare the changes in holdings:
https://13f.info/13f/000095012324005622/compare/000095012324005664

So to make this clear:

Q1-2024 shows this:
ISSUER NAME     | ... | SHARES
CHUBB LIMITED | ... | 25,923,840

Q4-2023 shows this (amendment):
ISSUER NAME     | ... | SHARES
CHUBB LIMITED | ... | 20.100.000

So from Q4-2023 to Q1-2024 they added: 5,823,840 Shares of CHUBB to their Portfolio.

Q3-2023 shows this:
ISSUER NAME     | ... | SHARES
CHUBB LIMITED | ... | 8.143.530

And from Q3-2023 to Q1-2024 they added 17.780.310 Shares of CHUBB to their Portfolio.

**So this is actually pretty easy, as each Filing is a stand alone. That makes the latest 13F-HR Filing the total holdings. There is nothing you need to add up to that.** 

So it makes sense to have a feature to just ignore 13F-HR/A amendment filings. I just want to have the latest 13F-HR Filing to do some quant calculations on the overall holdings, I don't really care about single changes in the portfolio.

So in the newest statement of Q1-2024 this is what they actualy hold now. In the amentment of Q4-2023 they bought 20,100,000 new shares of CHUBB as a new position and in the Q1-2024 they have bougth an additional 5,823,840 making it 25,923,840 now.

Edit: 
what you could do is, if the latest statement is an amendment that you add them up to the previous Filing or 13F-HR so we don't need to wait for an updated Version, if it doesnt exists yet. Like a aggregate_13f_filing or  compare_13f_filing. You could add the difference between the filings in terms of shares, value and percentage. But then would we want to compare also amentments with each other or only to 13F-HR filings? So their you could also have a ignore_amendments=False by default. 

Also would be great if its possible to have something like get_latest_13f_filing.filing_type that only returns the specific strings in the primary doc. E.g. 13F-HR/A - NEW HOLDINGS, 13F-HR/A - RESTATEMENT or 13F-HR.

**Comment by git-shogg** [comment]
Hey @philsv, thanks so much for clarifying that. I had a more detailed look through [the rules around amending 13F filings (questions 58a onwards)](https://www.sec.gov/divisions/investment/13ffaq#faq35) and what you've suggested is great. I've updated the package to take this into account by applying amendments forward. The library now properly separates 13F-HR filings from 13F-HR/A filings and defaults to applying amendments to all 13F-HR requests where they are available (this can just be turned off by passing `amend_filings` as False if you'd like to just read the original filing with no changes at all). If there are multiple amendments that have been made to a single filing, the script will iterate through them chronologically and add NEW HOLDINGS into the picture (updating cover page and holdings information) or if a RESTATEMENT is issued the previous state of filing will be completely overwritten with the new restatement details. 

I've updated the code and pushed to the 13f amendments feature branch. Can you trial it out using the [address_13f_amendments feature branch](https://github.com/git-shogg/finsec/tree/feature/address_13f_amendments) and let me know how it goes? After getting the all clear I will merge the change and push to pypi.

**Comment by philsv** [comment]
awesome work @git-shogg 👍

Only found one issue: ignore_amendments was still present for filing.latest_13f_filing_detailed. I have created a pull request for that.

Other then that I would say good to go, thanks for the new feature!

**Comment by git-shogg** [comment]
Thanks @philsv you're officially a contributor on the `finsec` package now! Closing this issue as PyPi is now updated with latest finsec package ready for install.
